CREATE TABLE IF NOT EXISTS todo_app.todo (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  todo VARCHAR(64) NOT NULL,
  index_number BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;
